### ISSUE TITLE
darts Window transformer

### ISSUE THREAD

**Issue by nagydavid** [JQGoh/multivariate_time_series_pipeline#1]
Hi @JQGoh 

I wonder if you have managed to do the same with the WindowTransformer from darts?

All the Best

D.

**Comment by JQGoh** [comment]
@nagydavid Hi, thanks for reading the article and checking this repository. I have not managed to get Window transformer working yet. 

I will update this repository and let you know once it is ready.

**Comment by nagydavid** [comment]
Thanks for the answer :)

**Comment by JQGoh** [comment]
@nagydavid 

Thanks for opening the issue. Please check the [changelog](https://github.com/JQGoh/multivariate_time_series_pipeline/tree/master#changelog) whereby I include an example of how to perform Darts window transformation using [DartsTransformers](https://github.com/JQGoh/multivariate_time_series_pipeline/blob/ec6a11d000bd5183d798f3bd242cc841b5deac05/src/features/darts_transformers.py#L79) class.

I am keen to learn more about how this project will benefit you. Hope this helps!

**Comment by nagydavid** [comment]
Hi @JQGoh,

Thanks a lot. I am using tsfresh to enrich univariate time series, where additional data can be used for covariates. I love the fact that tsfresh helps to extract additional info, but during inference I need to do it,  based on prediction step,  as shown in the [documentation](https://tsfresh.readthedocs.io/en/latest/text/forecasting.html).  Therefore I am interested to test your method and implement into "one-step prediction and feature extraction" encoder. 

:)
